language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=pep8
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=py27

install:
  - ./.travis/install

script:
- ./.travis/run tox


